export const LOAD_POPULAR_REPOS_REQUEST = 'LOAD_POPULAR_REPOS_REQUEST';
export const LOAD_POPULAR_REPOS_SUCCESS = 'LOAD_POPULAR_REPOS_SUCCESS';
export const LOAD_POPULAR_REPOS_FAILURE = 'LOAD_POPULAR_REPOS_FAILURE';

export const LOAD_REPO_DETAILS_REQUEST = 'LOAD_REPO_DETAILS_REQUEST';
export const LOAD_REPO_DETAILS_SUCCESS = 'LOAD_REPO_DETAILS_SUCCESS';
export const LOAD_REPO_DETAILS_FAILURE = 'LOAD_REPO_DETAILS_FAILURE';
